# SPDX-FileCopyrightText: The terraform-provider-git Authors
# SPDX-License-Identifier: 0BSD

FROM metio/devcontainers-go:latest

COPY --from=docker.io/hashicorp/terraform:latest /bin/terraform /usr/bin/terraform
RUN go install gotest.tools/gotestsum@latest
RUN go install github.com/golangci/golangci-lint/cmd/golangci-lint@master
