# git_remote resources can be imported by specifying the directory of the Git repository, the name of the remote and a
# list of its URLs separated by comma.
terraform import git_remote.remote directory|remote-name|first-url,second-url,...
