name: Automated Release
on:
  schedule:
    - cron: 47 2 * * FRI
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: commits
        name: Count Commits
        run: echo "::set-output name=count::$(git rev-list --count HEAD --since='last Friday' -- internal)"
      - id: tags
        name: Fetch all tags
        run: git fetch --force --tags
        if: steps.commits.outputs.count > 0
      - id: setup_go
        name: Set up Go
        uses: actions/setup-go@v3
        if: steps.commits.outputs.count > 0
        with:
          go-version-file: go.mod
          cache: true
      - id: import_gpg
        name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        if: steps.commits.outputs.count > 0
        with:
          gpg_private_key: ${{ secrets.GPG_SECRET_KEY_BASE64 }}
          passphrase: ${{ secrets.GPG_SECRET_KEY_PASSWORD }}
      - id: release
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3.0.0
        if: steps.commits.outputs.count > 0
        with:
          version: latest
          args: release --rm-dist
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
