name: Verify Commits
on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/verify.yml
      - go.mod
      - go.sum
      - main.go
      - internal/**
      - examples/**
      - docs/**
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/verify.yml
      - go.mod
      - go.sum
      - main.go
      - internal/**
      - examples/**
      - docs/**
jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: setup_go
        name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
      - id: generate_docs
        name: Generate Documentation
        run: go generate
      - id: verify_docs
        name: Verify Documentation
        run: |
          git diff --compact-summary --exit-code || \
            (echo "*** Unexpected differences after code generation. Run 'make generate' and commit."; exit 1)
      - id: build
        name: Build Provider
        run: go build -v ./...
  test:
    name: Run Tests on ${{ matrix.os }} with Terraform ${{ matrix.terraform }}
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest
        terraform:
          - 1.0.*
          - 1.1.*
          - 1.2.*
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: setup_go
        name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
      - id: setup_terraform
        name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false
      - id: tests
        name: Run Tests
        run: go test -v -cover -parallel=4 -timeout=120s ./internal/provider/
        env:
          TF_ACC: "1"
